{
 "title": "Glide Demo - HTTP req",
 "tags": [
  "e2e-coverage-api",
  "prometheus",
  "http-metrics"
 ],
 "time": { "from": "now-3h", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   { "name": "DS_PROMETHEUS", "label": "Data Source", "query": "prometheus" }
  ]
 },
 "panels": [
  {
   "title": "HTTP Request Average Duration",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "sum by (method, handler) (rate(http_request_duration_seconds_sum{handler!=\"/metrics\"}[1m])) / sum by (method, handler) (rate(http_request_duration_seconds_count{handler!=\"/metrics\"}[1m]))",
     "legendFormat": "({{method}}, {{handler}})"
    }
   ]
  },
  {
   "title": "HTTP Request Count by Endpoint",
   "type": "table",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "expr": "http_request_duration_seconds_count{handler!~\"/metrics\"}"
    }
   ]
  },
  {
   "title": "Average Request Time by Handler (1 week aggregation)",
   "type": "table",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "sum by(handler, method, job) (rate(http_request_duration_seconds_sum[1w])) / (sum by(handler, method, job) (rate(http_request_duration_seconds_count[1w])))"
    }
   ]
  },
  {
   "title": "HTTP Request Size (Average) - 5 min agg",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "rate(http_request_size_bytes_sum{handler!~\"/metrics\"}[5m]) / (rate(http_request_size_bytes_count[5m]))",
     "legendFormat": "{{handler}} - Avg Request Size"
    }
   ]
  },
  {
   "title": "HTTP Response Size (Average) - 5 min agg",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "rate(http_response_size_bytes_sum[5m]) / (rate(http_response_size_bytes_count[5m]))",
     "legendFormat": "{{handler}} - Avg Response Size"
    }
   ]
  },
  {
   "title": "HTTP Request Rate",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "rate(http_requests_total{handler!=\"/metrics\"}[5m])",
     "legendFormat": "{{handler}} {{method}} {{status}}"
    }
   ]
  }
 ]
}